"use strict";
var transportationModes = ["Honda motorcycle"];
console.log(`I would like to own a  ${transportationModes}.`);
var transportationModes = ["Range Rover car"];
console.log(`I dream of driving a ${transportationModes}.`);
var transportationModes = ["Bicycle"];
console.log(`Riding a ${transportationModes}  is so much fun!`);
var transportationModes = ["Private jet"];
console.log(`If I could afford it, I would buy a ${transportationModes}.`);
var transportationModes = ["Scooter"];
console.log(`Using a  ${transportationModes} for short trips would be convenient.`);
